export const neighborhoods = [
    { name: "Brandon Heights" },
    { name: "Castlegate" },
    { name: "Edelweiss Gardens" },
    { name: "Emerald Forest" },
    { name: "Dove Crossing" },
    { name: "Pebble Creek" },
    { name: "Southwood Valley" },
    { name: "Sun Meadows" },
    { name: "Bridle Gate Estates" },
    { name: "Southwood Forest" },
    { name: "Reatta Meadows" },
    { name: "Westfield Village" },
    { name: "Southern Trace" },
    { name: "Austin's Colony" },
]